const express = require("express");
const cors = require("cors");
const company = require("./routes/company.routes");
const errorMiddleware = require("./middlewares/error");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/v1/companies", company);
app.use(errorMiddleware);
module.exports = app;
